language: r
cache: packages
sudo: true
r_packages:
  - covr
r_binary_packages:
  - topicmodels

install:
- sudo apt-get install libgsl0-dev

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

before_install:
  - Rscript -e 'install.packages("devtools")'
  
after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
    slack: quanteda:W4x9WmNKqE7kVtkKZDWld7IP
