language: r
cache: packages
warnings_are_errors: true
sudo: true
r_packages:
  - covr
  - ExPosition
r_binary_packages:
  - topicmodels
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install libgsl0-dev
  - Rscript -e 'install.packages(c("devtools", "topicmodels", "tm"))'

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  
after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
    slack: quanteda:W4x9WmNKqE7kVtkKZDWld7IP
    
gcc:
  - "4.8"
