r_packages:
  - covr
  - knitr
  - rmarkdown

language: r
sudo: true

r_binary_packages:
- topicmodels
- testthat

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
  - Rscript -e 'library(covr);codecov()'

os:
  - linux
  - osx
  - windows
  