language: r
cache: packages
sudo: true
r_packages:
  - covr

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
    slack: quanteda:W4x9WmNKqE7kVtkKZDWld7IP
